apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: custom-aap-project-template
  title: Create Ansible Automation Platform Project
  description: Create a new starter AAP project Git project preconfigured with best practices.
  tags:
    - ansible
    - aap
    - project
spec:
  owner: group:default/architects
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - repoName
        - owner
      properties:
        sourceControl:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: github.com
          enum:
            - github.com
          enumNames:
            - 'GitHub'
        repoName:
          title: Playbook repository name
          description: The name of the new playbook project repository. For example, “my-new-playbook-repo”.
          type: string
          maxLength: 100
          pattern: '^([a-zA-Z][a-zA-Z0-9_]*)(-[a-zA-Z0-9_]+)*$'
        description:
          title: Playbook description
          type: string
          description: Describe the playbook and its purpose to help other users understand what to use it for.
          maxLength: 350
        owner:
          title: Catalog Owner name
          type: string
          description: The Red Hat Developer Hub catalog item owner. This will appear on the “My items” tab. For example, “my-devhub-username”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: The Red Hat Developer Hub system catalog item name. This will appear on the “My items” tab. For example, “my-devhub-system”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
  steps:
    - id: fetch-base-template
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./aap-project-skeleton
        values:
          repoName: ${{ parameters.repoName }}

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ./catalog-info/
        values:
          repoName: ${{ parameters.repoName }}
          repoUrl: github.com?owner=alexandremalo&repo=${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: aap-project
          description: ${{ parameters.description }}
          sourceControl: ${{ parameters.sourceControl }}
          devSpacesBaseUrl: https://devspaces.apps.cluster-j2rlm.j2rlm.sandbox1119.opentlc.com/#https://github.com/alexandremalo/${{ parameters.repoName }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - ${{ parameters.sourceControl }}
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=alexandremalo&repo=${{ parameters.repoName }}
        repoVisibility: 'public'
        defaultBranch: main
        protectDefaultBranch: false
        gitAuthorName: 'Red Hat Developer Hub'


    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
